TEAM-NXLL/Project-NXLL

js/body.js, js/main.js, js/route.js, member/detail.html, scss/detail.scss, scss/main.scss
- 마이쇼핑 페이지에서 로그인 상태에 따라 .information 영역 렌더하거나 하지 않기
- 첫 화면에서 로그인 상태 확인하고 인증이 유효하지 않으면 로컬 스토리지 비우기
=> feat: Modify check login state

js/body.js, member/detail.html, scss/detail.scss
- detail 페이지 안에 modal-payment로 장바구니 모달창 추가 (display:none으로 숨겨져있음. active 클래스 추가로 확인 가능)
=> feat: Create cart-modal in detail.html and Add detail.scss

admin/admin.html, admin/js/admin.js, admin/js/renderAllProducts.js, admin/js/renderAlltransacs.js, admin/js/renderProductTransacs.js, admin/js/requests.js, admin/scss/admin.scss, admin/scss/admin_common.scss, admin/scss/allProducts.scss, admin/scss/allTransac.scss, admin/scss/transacStatus.scss, index.html
admin.html을 커뮤니티 버튼 누르면 접근 가능하도록 해놨어요.
=> Feat: edit render function

js/body.js, js/main.js
=> Feat: 로그인 상태에 따른 잔액 조회

admin/admin.html, admin/js/admin-summary.js, admin/js/admin.js, admin/js/renderAllProducts.js, admin/js/requests.js, admin/scss/admin.scss, admin/scss/adminSummary.scss, admin/scss/allProducts.scss
- 거래 내역 관련 요약 정보
- 상품 관련 요약 정보
- html 내역 확인 버튼 삭제
=> Feat: create admin summary infomation area

js/main.js, scss/common.scss
=> feat: modyfied search block4

admin/admin.html, admin/js/addProduct.js, admin/js/editProduct.js
제품수정 이후 soldout상태가 false로만 api로 전송되던 오류 수정
제품수정 버튼 클릭 시 기존 정보가 input칸에 입력된 상태로 열리도록 기능 추가
(태그 체크박스는 수정중입니다.)
=> fix the editEvent function to check soldout state

admin/admin.html, admin/js/addProduct.js, admin/js/editProduct.js, admin/js/requests.js, admin/js/toast.js, admin/scss/addProducts.scss, admin/scss/allProducts.scss
수정페이지 진입 시 이전 선택 상품의 태그가 남아있는 오류 수정
=> Fix: fix the editInputPlaceholder function to show only received data

admin/scss/addProducts.scss, admin/scss/admin.scss, admin/scss/adminSummary.scss, admin/scss/allProducts.scss
=> Design: Change admin page CSS

admin/admin.html, admin/js/editProduct.js, index.html, js/main.js
- Add and rename product tags
- refactoring edit page placehoder function
=> Refactor: Add and rename product tags

js/main.js
main.js 코드 내 오타 수정 (태그별 섹션 정상 렌더링됩니다!)
=> Fix: bug fix of rendering main page

admin/admin.html, admin/js/admin.js, admin/js/renderAllProducts.js, admin/js/renderAlltransacs.js, admin/js/renderProductTransacs.js, admin/scss/admin.scss, admin/scss/allProducts.scss, admin/scss/productTransacs.scss
- 전체 제품 보기에서 개별 항목에 대한 거래내역 확인 가능하도록 함
- 렌더링 속도가 매우 느려, 일부 수정 필요
- 개별 제품 설명과 썸네일에 대한 div를 한번 더 감싸는 wrapper를 생성하고 scss를 변경하였습니다.
- 개별 아이템에 버튼이 생성되었습니다.
=> Feat: create renderProductTransac.js

js/body.js, js/detail.js, js/main.js, scss/detail.scss
=> feat: Add soldeout product function

admin/admin.html, admin/js/editProduct.js, admin/scss/addProducts.scss
상품 대분류를 위해 상품 추가/수정 페이지에 radio버튼 및 태그 추가
=> Feat: Add product tags in admin page

admin/js/renderAlltransacs.js, admin/js/renderProductTransacs.js, admin/scss/productTransacs.scss
- 거래 취소 및 거래 완료 버튼 클릭의 실행 오류 해결
- 거래 취소 및 거래 완료 버튼 scss 작업
=> Edit: edit renderProductTransacs.js for Cancel button

js/body.js, js/main.js
- 메인페이지 제외 모든 페이지 렌더시 스크롤 맨 위로 이동하기
- #myshop에서 로그인 아닌 상태일때 주문내역 조회 버튼 누르면 로그인 페이지로 연결
=> feat: Add render start scroll position function

admin/admin.html, admin/js/addProduct.js, admin/js/editProduct.js, index.html, js/main.js, js/route.js
- 상품 추가/수정페이지 카테고리 태그가 api에 잘못 전송되는 오류 수정
- 사용자페이지 카테고리별 상품 렌더링 기능 추가중
=> Fix: add/edit product page bug fix

admin/admin.html, admin/js/editProduct.js, admin/js/toast.js, admin/scss/allProducts.scss
- 상품 수정 후 이전 화면으로 되돌아갈 수 있도록 toast 팝업에 confirm 기능 추가
=> Feat: Add confirm function in the toast pop-up

js/detail.js, js/main.js, js/route.js, js/shoppingBag.js, scss/detail.scss
- 라우트 변경 될 때 마다 카트 수량 체크해서 값 변경하기
- 장바구니 비었을 때 대체 텍스트 보여주기
=> feat: Add cartCountCheck function and empty text

admin/js/editProduct.js, index.html, js/body.js, js/main.js, js/route.js, scss/main.scss
- 서브카테고리 렌더링 기능 추가
- 유튜브링크 추가
- 메뉴정렬, hover효과 등 디자인 약간 수정
=> Feat: Add sub category render function

index.html, js/body.js, js/main.js, js/route.js, scss/main.scss
- 메인메뉴 hover시 나타나는 패널메뉴에 상품목록조회 기능 연결
=> Feat: Add sort by hash function

admin/js/transacSearch.js
=> Fix: fix error of transacSearch.js

admin/admin.html, admin/js/addProduct.js, admin/js/delete.js, admin/js/editProduct.js, admin/js/requests.js, admin/js/toast.js, admin/scss/addProducts.scss
상품 추가/수정 페이지 라디오버튼에 required 속성 부여
상품 추가페이지 라디오버튼에 checked속성 부여
=> Feat: Add required attribute in the radio button

admin/admin.html, admin/js/addProduct.js, admin/js/requests.js, admin/js/toast.js
=> Fix: Admin page bug fix

admin/admin.html
-.jpg확장자 파일 업로드 가능 목록에 나오지 않던 오류 수정
=> Fix: Add upload file name extension (.jpg)

admin/js/addProduct.js, admin/js/toast.js
- 이미지 업로드 시 파일 확장자 유효성검사 기능 추가
- 상품 수정 후 화면 상단으로 스크롤 이동하는 오류 해결
=> Feat: Add upload file extensions validity check function

admin/js/addProduct.js, package-lock.json
- 상품추가페이지 중복코드 줄임
- querySelector 사용 줄임
=> Refactor: Refactoring admin page codes

admin/js/editProduct.js, admin/js/toast.js
=> Refactor: Refactoring toast.js, eidtProduct.js

admin/js/admin.js, admin/js/editProduct.js, admin/js/inputUtils.js, admin/js/submitUtil.js
- 관리자페이지 파일명 수정 (addProduct.js  -> inputUtils.js)
- 관리자페이지 add form, edit form에 사용하던 함수 합침, 새 파일 추가 (submitUtil.js)
=> Refactor: Refactoring admin page util functions

admin/js/admin.js, admin/js/delete.js, admin/js/submitUtil.js
- 관리자페이지 진입 시 에러로 authLogin 주석처리 (해당 부분에서 사용하는 함수 수정 필요)
=> Fix: temporary fixing

admin/js/admin.js, admin/js/adminSummary.js, admin/js/delete.js, admin/js/editProduct.js, admin/js/inputUtils.js, admin/js/renderAllProducts.js, admin/js/renderAlltransacs.js, admin/js/requests.js, admin/js/route.js, admin/js/submitUtil.js, admin/js/toast.js, admin/js/transacSearch.js, js/auth.js, js/body.js, js/detail.js, js/footer.js, js/main.js, js/myorder.js, js/payment.js, js/requests.js, js/shoppingBag.js, js/store.js, js/userInfo.js, util/store.js
- querySelector, getElementBy~ 유틸화
- 에러 발생 코드 수정
=> Refactor: Change querySelector as util, refactoring codes

js/detail.js, js/main.js, js/payment.js, js/shoppingBag.js, js/userInfo.js, util/requestAPI.js, util/store.js
- 상품 선택 체크 박스 오류 수정
- 상품 선택 시 금액 변경 오류 수정
=> Fix: 결제 페이지 코드 오류
